#!/bin/sh


echo "[+] Enter APN name [internet.telekom, etc ]:"
read -r apn 

while true
do
	echo "[+] Does the carrier need username and password? [Y/n]"
	read -r user_input
	
	case $user_input in
		[Yy]* )  while true 
        		do 
        
        			echo "[+] Enter username"
        			read -r username

        			echo "[+] Enter password"
        			read -r password
        			break 
        		done

        		break;;
		
		[Nn]* )  break;;
			*)  echo "[-] Select Y or n";;
	esac
done

echo "[+] Setting operation mode to online"
if ! qmicli -d /dev/cdc-wdm0 --dms-set-operating-mode='online';then
        echo "[-] Error: cdc-wdm0 mode to online"
        exit 1
fi


echo "[+]  Reconfigure the network interface for raw-ip protocol"

if ! ip link set wwan0 down;then
        echo "[-] Error: wwan0 down"
        exit 1
fi


if ! echo 'Y' | tee /sys/class/net/wwan0/qmi/raw_ip;then
        echo "[-] Error: raw IP mode"
        exit 1
fi

if ! qmicli -d /dev/cdc-wdm0 --wda-get-data-format;then
        echo "[-] Error: cdc-wdm0 data format"
        exit 1
fi 

if [  -z "$username" ]
then
	qmicli -p -d /dev/cdc-wdm0 --device-open-net='net-raw-ip|net-no-qos-header' --wds-start-network="apn=$apn,ip-type=4" --client-no-release-cid
else
   	qmicli -p -d /dev/cdc-wdm0 --device-open-net='net-raw-ip|net-no-qos-header' --wds-start-network="apn=$apn,username=$username,password=$password,ip-type=4" --client-no-release-cid
fi

echo "[+] Requesting IP..."
if ! udhcpc -q -f -i wwan0;then
        echo "[-] Error: dhcp request on wwan0"
fi

echo "[+] Internet connection is up"

exit 0
