#!/bin/bash

ALSA_CONFIG_ROUTE="/home/root/.asoundrc"
ALSA_DEVICE="hw:0,0"
ALSA_DSNOOP_PCM_NAME="mixin"

#rtsp
STREAMING_PORT=4444
STREAMING_BIT_RATE=128
STREAMING_SAMPLE_RATE=16000
STREAMING_CHANNELS=1
STREAMING_NAME="live"
RTSP_SERVER_PORT=1234
RTSP_SERVER_ADDRESS="127.0.0.1"
INPUT="dsnoop"
STREAM_AUDIO_CODEC="mpga"

TRANSCODE="#transcode{vcodec=none,acodec="$STREAMING_AUDIO_CODEC",ab="$STREAMING_BIT_RATE",channels="$STREAMING_CHANNELS",samplerate="$STREAMING_SAMPLE_RATE",scodec=none} \
:rtp{dst="$RTSP_SERVER_ADDRESS",port="$RTSP_SERVER_PORT",sdp=rtsp://"$RTSP_SERVER_ADDRESS":"$STREAMING_PORT"/"$STREAMING_NAME"}"

cvlc -vvv alsa://"$INPUT" --sout "$TRANSCODE"
